runtime: nodejs20 # Choose the appropriate runtime (e.g., python39, nodejs14, etc.)
handlers:
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|json|svg|woff|woff2|ttf|eot|map))$
    static_files: dist/\1
    upload: dist/(.*\.(js|css|png|jpg|jpeg|gif|ico|json|svg|woff|woff2|ttf|eot|map))$
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

env_variables:
  VUE_APP_FIREBASE_API_KEY: "AIzaSyD9DNAvs2Ryd-jTweyv2aF7OHegZN0b8JY"
  VUE_APP_FIREBASE_AUTH_DOMAIN: "my-grocery-home.firebaseapp.com"
  VUE_APP_FIREBASE_PROJECT_ID: "my-grocery-home"
  VUE_APP_FIREBASE_STORAGE_BUCKET: "my-grocery-home.appspot.com"
  VUE_APP_FIREBASE_MESSAGING_SENDER_ID: "888361723877"
  VUE_APP_FIREBASE_APP_ID: "1:888361723877:web:930792430b39fbd20df10c"
  VUE_APP_MEASUREMENT_ID: "G-QNMK83BJ7K"
