runtime: nodejs20 # Choose the appropriate runtime (e.g., python39, nodejs14, etc.)
handlers:
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|json|svg|woff|woff2|ttf|eot|map))$
    static_files: dist/\1
    upload: dist/(.*\.(js|css|png|jpg|jpeg|gif|ico|json|svg|woff|woff2|ttf|eot|map))$
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

env_variables:
  apiKey: "AIzaSyD9DNAvs2Ryd-jTweyv2aF7OHegZN0b8JY",
  authDomain: "my-grocery-home.firebaseapp.com",
  projectId: "my-grocery-home",
  storageBucket: "my-grocery-home.appspot.com",
  messagingSenderId: "888361723877",
  appId: "1:888361723877:web:930792430b39fbd20df10c",
  measurementId: "G-QNMK83BJ7K"
