steps:
  # Step to build the frontend
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]

  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]

  # Step to deploy the frontend to App Engine
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--quiet", "app.yaml"]

env_variables:
  FIREBASE_API_KEY: projects/888361723877/secrets/FIREBASE_API_KEY
  FIREBASE_AUTH_DOMAIN: projects/888361723877/secrets/FIREBASE_AUTH_DOMAIN
  FIREBASE_PROJECT_ID: projects/888361723877/secrets/FIREBASE_PROJECT_ID
  FIREBASE_STORAGE_BUCKET: projects/888361723877/secrets/FIREBASE_STORAGE_BUCKET
  FIREBASE_MESSAGINGSENDER_ID: projects/888361723877/secrets/FIREBASE_MESSAGINGSENDER_ID
  FIREBASE_APP_ID: projects/888361723877/secrets/FIREBASE_APP_ID
  FIREBASE_MEASUREMENT_ID: projects/888361723877/secrets/FIREBASE_MEASUREMENT_ID

timeout: "1600s"
